#-------------------------------
# General Site Settings

title: Anatoly Khalizev
description: Web Site Creator // Designer
email: ahalizev@gmail.com
phone_ru: Russia +79103113996
phone_cz: Czech +420736236791

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}
  #- {name: Русский, url: 'http://akhalizev.github.io/akhalizev-rus-blog/'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://akhalizev.github.io

seo:
  description: 'Web site development in Europe and Russia.'
  rel-author: 'https://plus.google.com/u/0/+ahalizev/'
  rel-publisher: 'https://plus.google.com/u/0/+ahalizev/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-57396995-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Anatoly making people's life better**
  I can create web site for you and your business (even if you need web store). Also I will promote it on search systems and social sites. If you need, I can design a logo.

skills:
- {name: UX Design, value: '7'}
- {name: Front End, value: '8'}
- {name: Programming, value: '4'}
- {name: Communication, value: '7'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '8'}

#-------------------------------
# Work Section

projects:
- {name: Valan Trade s.r.o. logo, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Copy Kursk site, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: 500px Photos, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Copy Kursk logo, folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
#- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-travis.png',
  name: 'Travis Neilson',
  title: 'DevTips creator, youtuber, web designer',
  quote: '<p><strong>I know Anatoly through an online community that I run.</strong> We are focused on web site design and development. Anatoly has shown himself to an an extremely engaged and thoughtful member, he is a valuable contributor to our community.</p>',
  logo: 'devtipslogo.png'}
- {avatar: 'face-akhalizev.png',
  name: 'Anatoly Khalizev',
  title: 'Director of Valan Trade, Czech and int.',
  quote: '<p><strong>Working with Anatoly was the highlight of my career.</strong> Ha-ha, here I am! And I know that work with me is very good chance for your to getting things done.</p>',
  logo: 'valan-logo-clients.png'}
- {avatar: 'face-lapin.jpg',
  name: 'Valentin Lapin',
  title: 'Director of Copy company, Kursk, RU',
  quote: '<p><strong>Anatoly creates our website,</strong> and we have a lot of new clients. He produce every part of work - from logo design to SEO.</p>',
  logo: 'copykursklogo.png'}
# - {avatar: 'face-teleject.jpg',
#   name: 'Cleatus Cassidy',
#   title: 'VP of Helmut, Lorem Sorem LLC.',
#   quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
#   logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/akhalizev/'}
- {icon: 'facebook-square', link: 'https://www.facebook.com/akhalizev'}
- {icon: 'behance', link: 'https://www.behance.net/akhalizev'}
- {icon: 'twitter-square', link: 'http://twitter.com/ahalizev'}
- {icon: 'instagram', link: 'https://instagram.com/ahalizev'}
- {icon: 'vk', link: 'https://www.vk.com/akhalizev'}
- {icon: 'cool', link: 'https://about.me/akhalizev'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
